### ISSUE TITLE
String data becomes binary after "convert_dictionary_to_ros_message"

### ISSUE THREAD

**Issue by maksutovaynur** [uos/rospy_message_converter#26]
![image](https://user-images.githubusercontent.com/12110033/52431084-8873a300-2b18-11e9-95ee-92fddf3fade2.png)

In python3

**Comment by maksutovaynur** [comment]
Where M = std_msgs.msg, MC = rospy_message_converter.message_converter

**Comment by mintar** [comment]
This is the correct behavior. ROS message fields of type "string" correspond to the Python3 type "bytes", see here:

http://wiki.ros.org/msg#Fields

One peculiarity is that you can put anything into a message field when you create it, e.g.:

```python
ms1 = std_msgs.msg.String("Hello")
ms2 = std_msgs.msg.String(3)
ms3 = std_msgs.msg.String(b"Hello")
```

All of this will work, but when you try to serialize ms1 or ms2 (such as when you try to publish it), an exception will be thrown, because a ROS string field cannot hold a python `str` or `int`. Publishing ms3 will succeed.
