### ISSUE TITLE
Plans on ROS2 Support

### ISSUE THREAD

**Issue by mikelyndersOKCC** [uos/rospy_message_converter#28]
Hello, are there plans to expand this to ROS2 and rclpy? By the package name (rospy) it may be misleading, although useful, to also support rclpy. Would PRs be accepted for this purpose?

**Comment by mintar** [comment]
Sorry for the late reply, I'm super busy at the moment. ROS2 support would be awesome, and I would be glad to merge PRs to that effect! It's probably best if you open the PR against the master branch at first; I'll create a `ros2` or `eloquent` branch before merging.

**Comment by nyxaria** [comment]
Hi, is there any update on this? It would be great to have this functionality.

See these for implementation ideas:

https://github.com/ros2/ros2/issues/857#issuecomment-680996280
https://answers.ros.org/question/359681/generic-subscriber-in-ros2/
https://answers.ros.org/question/346810/ros2-python-add-arguments-to-callback/
https://stackoverflow.com/questions/13303100/how-to-access-the-class-variable-by-string-in-python

**Comment by mintar** [comment]
I'm willing to accept pull requests for this, but there has been nobody stepping up so far.

**Comment by yfedi** [comment]
Hello all,

I did some research and tried to port this solution to ROS2.
So, I have a solution, but it doesn't work for all scenarios. In ROS2 we are not allowed to create field names in msg file with uppercase(https://github.com/ros2/rosidl/pull/25), so if JSON has fields with uppercase(e.g. {"Test":"data"}), convertation to ROS2 msg will fail. 
In ROS1 we don't have such restriction and we are able to create field name "Test".

So far, I don't see "easy" solution for this .

BR,
Yuriy

**Comment by nyxaria** [comment]
Do you have code which shows the solution you tried? Maybe I can help @yfedi

**Comment by mintar** [comment]
> In ROS2 we are not allowed to create field names in msg file with uppercase(ros2/rosidl#25), so if JSON has fields with uppercase(e.g. {"Test":"data"}), convertation to ROS2 msg will fail.

That shouldn't be a problem. `rospy_message_converter` fills out ROS message fields from a JSON dictionary; if the message doesn't have a matching field for some key in the dict, conversion fails. So for example, if I have a dict like `{"Test":"data"}` and try to convert it into a [`geometry_msgs/Point`](http://docs.ros.org/en/melodic/api/geometry_msgs/html/msg/Point.html), conversion will fail because `Point` doesn't have a field called `Test`. So it doesn't matter if the field `Test` just isn't present in the message definition, or if it's even impossible to specify uppercase field names. All that matters is that the field isn't present, so conversion fails (as expected).

**Comment by yfedi** [comment]
Let's imagine the next situation, where we have a predefined JSON structure and this JSON is received in ROS2. So I would like to use ROS2 msg inside ROS instead of JSON string, as this message should be spread to different nodes.

If we have predefined JSON like `"{"test_fieldname": "name"}"`, so we can create custom ROS2 msg test_msgs/TestMsg: `string test_fieldname`
In this situation, we are able to fill out ROS message fields from a JSON dictionary:
```python
json_str = '{"test_fieldname": "name"}'
message = json_message_converter.convert_json_to_ros_message('test_msgs/TestMsg', json_str) 
```

But what if the JSON structure has a field names like `testFieldname`? We are not allowed to create custom ROS2 msg test_msgs/TestMsg: `string testFieldname` and we can't converse this JSON to ROS2 msg using `rospy_message_converter`.

Sure, we have different solutions for this, like changing JSON field names to lowercase or parse JSON messages and fill the ROS2 msg field by field. But those methods are not so great as the solution provided by `rospy_message_converter`

**Comment by mintar** [comment]
The convention for ROS message fields is that they should always be lower case: http://wiki.ros.org/ROS/Patterns/Conventions#Messages. I'm glad that ROS2 finally enforces that. So yes, you're right, you'll have to change the JSON field names. But that's much better than creating a ROS message definition that is not standards compliant.

**Comment by dheera** [comment]
Here's what I do for converting ROS2 messages to JSON

```
#!/usr/bin/env python3

import numpy as np
import array

def ros2dict(msg):
    if type(msg) in (str, bool, int, float):
        return msg

    output = {}
    for field in msg.get_fields_and_field_types():
        value = getattr(msg, field)
        if type(value) in (str, bool, int, float):
            output[field] = value

        elif type(value) is list:
            output[field] = [ros2dict(el) for el in value]

        elif type(value) in (np.ndarray, array.array):
            output[field] = [ros2dict(el) for el in value.tolist()]

        else:
            output[field] = ros2dict(value)

    return output
```

**Comment by ljaniec** [comment]
I have found [this repository](https://github.com/mehmetkillioglu/ros2_message_converter/tree/master) with the update of this package to ROS 2. Maybe you could contact with it's author (@mehmetkillioglu) for PR + possible updates and debug?

**Comment by mehmetkillioglu** [comment]
Thank you for finding my repository and opening a PR. I will soon update and test the codes. The main use-case for my fork is to handle messages during communication with MiR100 mobile robot, which has a ROS1 based "rosbridge_suite" acting as a WebSocket server. I will update the package to be more generic and not specifically for our use case.

**Comment by relffok** [comment]
I forked and ported this to foxy (also for MiR support) a while ago as well and didn't see this conversation. I just opened a PR. I hope someone can find something useful in it or maybe give feedback on it: https://github.com/uos/rospy_message_converter/pull/56

**Comment by ljaniec** [comment]
Any update on this PR #56 ?

**Comment by mintar** [comment]
@ljaniec : You can help by testing the PR and reviewing the code, documenting what works and what doesn't and submitting bugfixes. I won't have time before the end of January unfortunately.

**Comment by Interpause** [comment]
I discovered functionality for conversion to and between Python dictionaries (& consequently JSON) seem to be present in [`rosidl_runtime_py`](https://github.com/ros2/rosidl_runtime_py):

https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/set_message.py#L28-L37

https://github.com/ros2/rosidl_runtime_py/blob/1979f566c3b446ddbc5c3fb6896e1f03ccbc6a27/rosidl_runtime_py/convert.py#L159-L176

Honestly, ROS2's Documentation is a mess.

**Comment by mintar** [comment]
I have just finished converting [uos/rospy_message_converter](https://github.com/uos/rospy_message_converter/) to ROS2 and released it (as `rclpy_message_converter`) to ROS2 foxy, galactic, humble and rolling. It should be available as binary package after the next sync.
