### ISSUE TITLE
latest version can't use 0/1 as bool

### ISSUE THREAD

**Issue by corot** [uos/rospy_message_converter#40]
So messages properly parsed before are not anymore.
I understand that this is reasonable option... so fill free to close if it has been an intended change.

**Comment by mintar** [comment]
This is similar to #39. Do you have any comments on my proposed fix over there? I'm not quite sure what the right thing to do is, that's why I haven't pushed it yet. Maybe I should also allow ints for bool (which would fix this issue)? Or maybe I shouldn't allow floats for the integer types over there?

**Comment by mintar** [comment]
Upon reflection, I think it's better to force the programmer to explicitly convert their ints to bools, if that's ok for you. I'm going to close it for now. Feel free to reopen if there's more.

**Comment by corot** [comment]
Sure, sure;  is strict but reasonable. I already adapted my code to convert. Thanks!
